### ISSUE TITLE
Separate Docker step for `pip install -r requirements.txt`

### ISSUE THREAD

**Issue by tintinnabulate** [AaLondon/aalondon#133]
At the moment, it seems like the long  `sh` command in the Dockerfile means that whenever requirements.txt changes, we have to run the whole command again.

I wonder if we should put `pip install -r requirements.txt` in it's own RUN step so that we can make Docker cache all the apt-get stuff and speed up builds. I don't care about apt-get purging $buildDeps (yes the image will be bigger if we don't purge, but we're much more likely to change requirements.txt than change $buildDeps)

**Comment by chriswedgwood** [comment]
Raise a PR and lets try it 👍
