### ISSUE TITLE
Docker container failing

### ISSUE THREAD

**Issue by tintinnabulate** [AaLondon/aalondon#154]
![2020-07-28-162026_2560x1470_scrot](https://user-images.githubusercontent.com/34038724/88685951-71e75000-d0ee-11ea-9218-41786a0d39d9.png)

**Comment by tintinnabulate** [comment]
@chriswedgwood  any ideas?

**Comment by chriswedgwood** [comment]
have you run the migrate command?

**Comment by tintinnabulate** [comment]
oops.. that was the problem! Thanks :)

**Comment by chriswedgwood** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make zoom item clickable and make it obvious in details what is clickable(url)](https://trello.com/c/XvQHe6DQ/156-make-zoom-item-clickable-and-make-it-obvious-in-details-what-is-clickableurl)
