### ISSUE TITLE
UX improvement: Give meeting title URL an obvious colour / font / weight

### ISSUE THREAD

**Issue by tintinnabulate** [AaLondon/aalondon#155]
At the moment, the URL for the meeting Title has the same colour / font & weight as all the other text, so it's not clear that it's a link.

My suggestion is to give it a different colour & weight (bold) so that it's really obvious this is a link. Perhaps even give it a different font?

Screenshot included below:

![url_aalondon](https://user-images.githubusercontent.com/34038724/89105336-1da6dd80-d418-11ea-97f5-30e90671fd9c.png)

**Comment by chriswedgwood** [comment]
Might be better adding this on trello? That way Javier and Alan can have input?

**Comment by tintinnabulate** [comment]
@chriswedgwood added on Trello now
