### ISSUE TITLE
Is `oa` field binary or ternary?

### ISSUE THREAD

**Issue by tintinnabulate** [AaLondon/aalondon#199]
Currently, the interpretation of the `oa` field in the meetingfinder scrape is that `oa` is a binary value:

``` { .python }
# from scraper/spiders/meeting_spider.py
marker_open_again = meeting.get('oa')
if marker_open_again == 'True':
    covid_open_status = True
else:
    covid_open_status = False
```

However, it seems to me like it's a ternary value, i.e. it has three states: `''` , `True` , `False`  .

Do we definitely know that `''` and `False` are equivalent? Why are some set to `''` and others set to `'False'`?

**Comment by chriswedgwood** [comment]
It comes into us a a string with three potential states '','True','False'. From our perspective a binary is correct as it is either open again/ not.

I saw it this way:
 '' -> False
'False' -> False
'True' -> True

**Comment by tintinnabulate** [comment]
I had a thought that `''` means that the meeting never reported their meeting as being shut.

**Comment by chriswedgwood** [comment]
Yes so if it’s an empty string I make False so it won’t be seen as open on
our site.
Assume closed unless explicitly told otherwise
