### ISSUE TITLE
Alan reporting meetings coming up as inactive when are active on aa-gb

### ISSUE THREAD

**Issue by chriswedgwood** [AaLondon/aalondon#225]
This suggests the scrape is not setting these to active in our system

**Comment by chriswedgwood** [comment]
<marker title="Recovery goes Rogue in Ally Pally" time="18.30 - duration 1hr" postcode="N22 7AY" lat="51.5921757" lng="-0.1370354" address="The log near Giro's Cafe in The Grove. https://w3w.co/rested.smoke.lately" oa="False" code="15351" day="Tuesday" hearing="0" wheelchair="1" sign="0" ms="5" ci="" slng="" slat=""/>

This is reporting oa is False and the scraper assumes it is not open again but the aa-gb website reports that it is open.

![image](https://user-images.githubusercontent.com/1273523/100634108-c6ae0800-3326-11eb-8c6e-f0e5624f85ee.png)

I will need to adjust the scrape logic

**Comment by tintinnabulate** [comment]
@chriswedgwood Weird. Is `oa="False"` on aa gb?

**Comment by chriswedgwood** [comment]
I was thinking that I could work out from here if it is open again but I cant so we are at the mercy of oa=.


https://www.alcoholics-anonymous.org.uk/detail.do?id=15351

**Comment by chriswedgwood** [comment]
![image](https://user-images.githubusercontent.com/1273523/100637330-a8e2a200-332a-11eb-8a51-2f3466fd7934.png)

**Comment by tintinnabulate** [comment]
> ms= is the new flag
> ![image](https://user-images.githubusercontent.com/1273523/100637330-a8e2a200-332a-11eb-8a51-2f3466fd7934.png)

@chriswedgwood  What URL did you visit to get this screenshot?

**Comment by chriswedgwood** [comment]
I got this from the Eclo’s trustee who got it from Silverink
