### ISSUE TITLE
Add button to site that creates an app link on phone (Trello issue 87)

### ISSUE THREAD

**Issue by tintinnabulate** [AaLondon/aalondon#68]
https://pypi.org/project/django-pwa/

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen

https://stackoverflow.com/questions/55104450/where-should-pwa-manifest-be-located-for-a-django-app

**Comment by tintinnabulate** [comment]
I can't seem to get `django-sslserver` working 😞  - I when I open https://0.0.0.0:8000 in Firefox I get `SSL_ERROR_RX_RECORD_TOO_LONG`. 

and this doesn't seem to help: https://www.thesslstore.com/blog/ssl_error_rx_record_too_long/

Can you show me how to deploy to staging so I can test the "Add To Homescreen" feature there?

**Comment by chriswedgwood** [comment]
If you raise a PR against staging I can run a deployment from my mac. I have some ansible that I havent yet checked in I can use. Im keen to get that automated.

**Comment by tintinnabulate** [comment]
Abandoning this for now, in light of higher priority issues.
