### ISSUE TITLE
CI is non-existstent and staging deployments need to be automated

### ISSUE THREAD

**Issue by chriswedgwood** [AaLondon/aalondon#88]
I have played a little with github actions but need to spend some time to improve automation with CI/CD

**Comment by tintinnabulate** [comment]
I strongly approve of this issue being worked on 😃 

Do you plan to do anything in addition to deploying to `staging`?

As for platforms, I've used [TravisCI](https://travis-ci.org) and it's good. You can add any secret environment variables like so: 

<https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml>

**Comment by chriswedgwood** [comment]
I use travisCI for my other projects CI
At the moment I am deploying using ansible from my mac but wanted to automate both staging and production deployments. Also we have no testing at the moment so was wanting to learn how to integrate ansible with github actions(which seem to be the new kid in the block) or TravisCI.
If you have implemented anything like this before I would love to discuss.

**Comment by tintinnabulate** [comment]
I've never used Ansible, or Github actions.

I've got a decent amount of experience with doing unit testing, dependency injection, `mock`, and end-to-end web application testing with Python & Flask. Nothing with Django. And it's been a while... but I suspect a lot of the things I've been doing in Go and in my dayjob are transferrable concepts, at least high-level.

**Comment by tintinnabulate** [comment]
Hi Chris,

If you walk me through how you currently deploy to staging manually, I can have a go at doing it automatically.

I've recently had some experience of encrypting secret config info using https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml .

**Comment by chriswedgwood** [comment]
Hi 👋 I do it through an ansible playbook.

I’m away this weekend can we have a zoom session next week and I can show
you.

I  keep intending to automate it after a merge to staging but haven’t had
the time yet.

What times are good for you?

**Comment by tintinnabulate** [comment]
We can now deploy to Staging with Github Actions

Closed by the following PRs: #119 #120 #121 #122

I propose that we create a new, separate issue, regarding a CI testsuite.
